name: yaca
description: Yet Another Cellular Automaton engine written in Dart.
version: 0.0.0+1
homepage: https://github.com/alestiago/cellular_automata/tree/main/dart/cellular_automaton

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  meta: ^1.8.0

dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.0
